export const SELECT_GISTS_OWNER = 'SELECT_GISTS_OWNER'

export const FETCH_GISTS = 'FETCH_GISTS'
export const RESOLVE_GISTS = 'RESOLVE_GISTS'
export const REJECT_GISTS = 'REJECT_GISTS'

export const FETCH_GIST_CONTENT = 'FETCH_GIST_CONTENT'
export const RESOLVE_GIST_CONTENT = 'RESOLVE_GIST_CONTENT'
export const REJECT_GIST_CONTENT = 'REJECT_GIST_CONTENT'
export const DESTROY_GIST_CONTENT = 'DESTROY_GIST_CONTENT'

export const CHANGE_EDITING_GIST_CONTENT = 'CHANGE_EDITING_GIST_CONTENT'
export const UPDATE_GIST_CONTENT = 'UPDATE_GIST_CONTENT'
export const RESOLVE_UPDATE_GIST_CONTENT = 'RESOLVE_UPDATE_GIST_CONTENT'
export const REJECT_UPDATE_GIST_CONTENT = 'REJECT_UPDATE_GIST_CONTENT'
