export const CHANGE_GIST_CRITERIA = 'CHANGE_GIST_CRITERIA'

export const LIST_GISTS = 'LIST_GISTS'
export const LIST_NEXT_GISTS = 'LIST_NEXT_GISTS'

export const READ_GIST = 'READ_GIST'
export const CREATE_GIST = 'CREATE_GIST'
export const UPDATE_GIST = 'UPDATE_GIST'

export const NEW_EDITING_GIST = 'NEW_EDITING_GIST'
export const CHANGE_EDITING_GIST = 'CHANGE_EDITING_GIST'
