export const SELECT_GISTS_OWNER = 'SELECT_GISTS_OWNER'

export const FETCH_GISTS = 'FETCH_GISTS'
export const FETCH_GISTS_RESOLVED = 'FETCH_GISTS_RESOLVED'
export const FETCH_GISTS_REJECTED = 'FETCH_GISTS_REJECTED'

export const FETCH_GIST = 'FETCH_GIST'
export const FETCH_GIST_RESOLVED = 'FETCH_GIST_RESOLVED'
export const FETCH_GIST_REJECTED = 'FETCH_GIST_REJECTED'
export const DESTROY_FETCHED_GIST = 'DESTROY_FETCHED_GIST'

export const CREATE_EDITING_GIST = 'CREATE_EDITING_GIST'
export const CHANGE_EDITING_GIST = 'CHANGE_EDITING_GIST'
export const DESTROY_EDITING_GIST = 'DESTROY_EDITING_GIST'

export const CREATE_GIST = 'CREATE_GIST'
export const CREATE_GIST_RESOLVED = 'CREATE_GIST_RESOLVED'
export const CREATE_GIST_REJECTED = 'CREATE_GIST_REJECTED'
export const DESTROY_CREATED_GIST = 'DESTROY_CREATED_GIST'

export const UPDATE_GIST = 'UPDATE_GIST'
export const UPDATE_GIST_RESOLVED = 'UPDATE_GIST_RESOLVED'
export const UPDATE_GIST_REJECTED = 'UPDATE_GIST_REJECTED'
export const DESTROY_UPDATED_GIST = 'DESTROY_UPDATED_GIST'
